### ISSUE TITLE
Removing extension?

### ISSUE THREAD

**Issue by k0nsl** [s9e/phpbb-ext-reckless#1]
If I were to install this extension (I have admittedly not reviewed the code yet), would there be any issues at all if I were to disable it and then get rid of it, for whatever reason?

Thanks in advance and thank you for what appears to be an interesting and useful extension.

**Comment by JoshyPHP** [comment]
I *think* you can uninstall it just fine but I would definitely not recommend installing it on a live environment without testing it on a development board that you don't mind nuking/reinstalling.

Mostly I use this extension to test some ideas, the repository isn't stable and some commit may break it randomly.

**Comment by k0nsl** [comment]
Thank you. I will follow your recommendation.
